# 服务配置
server:
  servlet:
    context-path: /sso
  port: 8500

# spring 配置
spring:
  profiles:
    active: sso
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    # 浏览器是否缓存
    cache: false
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: classpath:/static/**
  datasource:
    url: jdbc:mysql://123.56.144.215:3306/sso_server?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql-server
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 123.56.144.215 # Redis服务器地址
    #    host: localhost
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: redis-server # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

# mybatis 配置
mybatis:
  # mybatis 接口映射 xml 文件路径
  mapper-locations: classpath*:/mybatis/**/*Mapper.xml
  # 搜索指定包别名
  type-aliases-package: cn.cy.server.**.entity
  # mybatis全局配置文件路径
  configLocation: classpath:mybatis/mybatis-config.xml

# Jwt 配置
jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  iss: "SSO_SERVER"
  secret: "qwertyuiop7418520" #密钥
  expireTime: 3600000 #token有效时间 (分钟) 建议一小时以上


logging:
  level:
    #   配置打印sql到控制台
    root: info
    cn.cy.server: debug