sso-core:
  type: server

sso-server:
  origin-password: "123456789"
  user-cache-key: "user"
  app-cache-key: "app"
  exclude:
    - /
    - /login
    - /error
    - /auth
    - /callback/**
    - /static/**
